# Generated by Django 4.0.4 on 2023-08-31 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pos', '0002_alter_stockproperty_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockproperty',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
