# Generated by Django 4.0.4 on 2023-08-31 09:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Pos', '0003_stockproperty_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='date_employed',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
