# Generated by Django 4.0.4 on 2023-09-01 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pos', '0004_employees_date_employed'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
