# Generated by Django 4.0.4 on 2023-09-01 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pos', '0005_cart_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='delivered',
            field=models.BooleanField(default=False),
        ),
    ]
