# Generated by Django 4.0.4 on 2023-09-02 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pos', '0007_remove_workinprogress_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockproperty',
            name='size',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='stockproperty',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='workinprogress',
            name='size',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
