# Generated by Django 4.0.4 on 2023-09-02 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pos', '0008_alter_stockproperty_size_alter_stockproperty_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockproperty',
            name='extrasize',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
    ]
