# Generated by Django 4.0.4 on 2023-09-02 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pos', '0009_stockproperty_extrasize'),
    ]

    operations = [
        migrations.AddField(
            model_name='workinprogress',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
