# Generated by Django 4.0.4 on 2023-09-03 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pos', '0010_workinprogress_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='workinprogress',
            name='product_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='workinprogress',
            name='product_size',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
