# Generated by Django 4.0.4 on 2023-09-03 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pos', '0011_workinprogress_product_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='reset',
            field=models.BooleanField(default=False),
        ),
    ]
