# Generated by Django 4.0.4 on 2023-09-04 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pos', '0012_expenses_reset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockproperty',
            name='extrasize',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
