# Generated by Django 4.0.4 on 2023-10-19 07:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Pos', '0016_workinprogress_productquantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpro',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 10, 19, 7, 17, 28, 845326, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
