# Generated by Django 4.0.4 on 2023-11-24 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pos', '0018_customer_date_added_employees_date_added_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockproperty',
            name='buying_price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
