# Generated by Django 4.0.4 on 2023-11-28 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pos', '0019_stockproperty_buying_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockproperty',
            name='buying_price',
        ),
    ]
