# Generated by Django 4.0.4 on 2023-12-10 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pos', '0020_remove_stockproperty_buying_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockproperty',
            name='buying_price',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
