# Generated by Django 4.0.4 on 2023-12-10 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pos', '0023_alter_stockproperty_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockproperty',
            name='extrasize',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='stockproperty',
            name='size',
            field=models.DecimalField(decimal_places=50, max_digits=1000),
        ),
    ]
