# Generated by Django 4.0.4 on 2023-12-10 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pos', '0024_alter_stockproperty_extrasize_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockproperty',
            name='total',
            field=models.DecimalField(decimal_places=20, default=0.0, max_digits=1000),
        ),
    ]
