# Generated by Django 4.0.4 on 2023-12-10 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pos', '0025_alter_stockproperty_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockproperty',
            name='total',
            field=models.DecimalField(decimal_places=200, default=0.0, max_digits=1000),
        ),
    ]
