# Generated by Django 4.0.4 on 2024-10-06 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pos', '0027_alter_cart_deposited_alter_productpro_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('total_sales_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('cash_sales', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
