# Generated by Django 4.0.4 on 2024-10-07 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pos', '0028_salesanalytics'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesanalytics',
            name='number_of_orders',
            field=models.IntegerField(default=0),
        ),
    ]
