# Generated by Django 4.0.4 on 2024-10-20 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pos', '0031_alter_customer_date_added'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('material_size', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product', models.CharField(max_length=200)),
                ('product_size', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField()),
                ('material_to_use', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pos.stockproperty')),
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='salesanalytics',
            name='cash_sales',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=115),
        ),
        migrations.AlterField(
            model_name='salesanalytics',
            name='total_sales_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=115),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.TextField()),
                ('estimated_pay', models.DecimalField(decimal_places=2, max_digits=10)),
                ('levels', models.IntegerField(blank=True, null=True)),
                ('start_date', models.DateTimeField()),
                ('due_date_time', models.DateTimeField()),
                ('completed', models.BooleanField(default=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pos.projectname')),
            ],
        ),
    ]
