# Generated by Django 4.0.4 on 2024-10-20 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pos', '0033_task_date_create'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='date_create',
            new_name='date_created',
        ),
    ]
