# Generated by Django 4.0.4 on 2024-10-21 03:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Pos', '0034_rename_date_create_task_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectname',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
