# Generated by Django 4.0.4 on 2024-10-31 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pos', '0037_alter_task_assigned_to_advances'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='id_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
