# Generated by Django 4.0.4 on 2024-11-03 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pos', '0039_rename_levels_task_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
