# Generated by Django 4.0.4 on 2024-11-03 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pos', '0040_alter_task_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_completed',
            field=models.IntegerField(default=0),
        ),
    ]
