# Generated by Django 4.0.4 on 2024-11-04 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pos', '0041_task_task_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_size', models.DecimalField(decimal_places=2, max_digits=10)),
                ('material_to_use', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pos.stockproperty')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='Pos.projectname')),
            ],
        ),
    ]
