# Generated by Django 4.0.4 on 2024-11-05 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pos', '0043_remove_projectname_material_size_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjectMaterial',
            new_name='TaskMaterial',
        ),
        migrations.RemoveField(
            model_name='taskmaterial',
            name='project',
        ),
        migrations.AddField(
            model_name='taskmaterial',
            name='task',
            field=models.ForeignKey(default=25, on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='Pos.task'),
            preserve_default=False,
        ),
    ]
