# Generated by Django 4.0.4 on 2024-11-07 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pos', '0045_alter_productsize_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='customer',
        ),
        migrations.AddField(
            model_name='cart',
            name='customer',
            field=models.ManyToManyField(to='Pos.customer'),
        ),
    ]
