# Generated by Django 4.0.4 on 2024-11-07 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pos', '0046_remove_cart_customer_cart_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='customer',
        ),
        migrations.AddField(
            model_name='cart',
            name='customer',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='Pos.customer'),
            preserve_default=False,
        ),
    ]
