# Generated by Django 4.0.4 on 2024-11-12 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pos', '0049_productsize_alphabetic_size_alter_productsize_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsize',
            name='size',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
