# Generated by Django 4.0.4 on 2024-11-15 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pos', '0051_rename_taskmaterial_projectmaterial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='Pos.projectname'),
        ),
    ]
