# Generated by Django 4.0.4 on 2024-11-18 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pos', '0052_alter_task_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsize',
            name='size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
